version: "3.9"

services:
  web:
    env_file:
      - .env
    build: .
    container_name: shorturl_web
    restart: always
    ports:
      - "80:8080"
    command: python main.py

  tbot:
    env_file:
      - .env
    build: .
    container_name: shorturl_bot
    restart: always
    command: python bot.py

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
